### ISSUE TITLE
scene.camera is undefined

### ISSUE THREAD

**Issue by tomalrussell** [tangrams/lights-cameras-demo#2]
Playing with the demo in Firefox 46.0.1, any change to the camera controls triggers an error on line 52 in main.js:
"scene.camera is undefined"

A quick fix in the console seems to get things working:
scene.camera = scene.config.cameras[scene.getActiveCamera()]

**Comment by meetar** [comment]
You're right, thanks for the catch! Fixed with https://github.com/tangrams/lights-cameras-demo/commit/b09424bbdf564eba803cc50a0c6047577b60cdc5
